.TH "src Directory Reference" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBasicComparator\&.cpp\fP"
.br
.RI "\fIDefault comparation method\&. \fP"
.ti -1c
.RI "file \fBBasicComparator\&.h\fP"
.br
.RI "\fIDefault comparation method\&. \fP"
.ti -1c
.RI "file \fBBasicLoader\&.cpp\fP"
.br
.RI "\fIDefault web browser start and image acquire methods\&. \fP"
.ti -1c
.RI "file \fBBasicLoader\&.h\fP"
.br
.RI "\fIDefault web browser start and image acquire methods\&. \fP"
.ti -1c
.RI "file \fBcomparator_traits\&.h\fP"
.br
.RI "\fITraits header for comparator objects\&. \fP"
.ti -1c
.RI "file \fBloader_traits\&.h\fP"
.br
.RI "\fITraits and defines for loader objects\&. \fP"
.ti -1c
.RI "file \fBmisc\&.h\fP"
.br
.RI "\fIMiscellaneous common defines\&. \fP"
.ti -1c
.RI "file \fBpflow\&.h\fP"
.br
.RI "\fIMiscellaneous common defines\&. \fP"
.ti -1c
.RI "file \fBwpc\&.h\fP"
.br
.in -1c
