.TH "src/BasicLoader.cpp" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/BasicLoader.cpp \- 
.PP
Default web browser start and image acquire methods\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BasicLoader\&.h'\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SH "Detailed Description"
.PP 
Default web browser start and image acquire methods\&. 


.PP
Definition in file \fBBasicLoader\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
