.TH "src/BasicComparator.h" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/BasicComparator.h \- 
.PP
Default comparation method\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'comparator_traits\&.h'\fP
.br
\fC#include <boost/signals2\&.hpp>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwpc::cmp_trait< BasicComparator >\fP"
.br
.ti -1c
.RI "class \fBwpc::BasicComparator\fP"
.br
.RI "\fIDefines basic class for comparison of two selected web page fragments\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Default comparation method\&. 


.PP
Definition in file \fBBasicComparator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
