.TH "src/BasicComparator.cpp" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/BasicComparator.cpp \- 
.PP
Default comparation method\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BasicComparator\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Default comparation method\&. 


.PP
Definition in file \fBBasicComparator\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
