.TH "src/BasicLoader.h" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/BasicLoader.h \- 
.PP
Default web browser start and image acquire methods\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'misc\&.h'\fP
.br
\fC#include 'loader_traits\&.h'\fP
.br
\fC#include 'BasicComparator\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwpc::BrowserData\fP"
.br
.RI "\fIBrowser descriptor for \fBBasicLoader\fP\&. \fP"
.ti -1c
.RI "struct \fBwpc::BasicLoaderAppData\fP"
.br
.RI "\fIBrowser descriptor for \fBBasicLoader\fP\&. \fP"
.ti -1c
.RI "struct \fBwpc::LayerData\fP"
.br
.RI "\fILayer descriptor\&. \fP"
.ti -1c
.RI "class \fBwpc::BasicLoader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< BrowserData > \fBwpc::BrowserDataVector\fP"
.br
.ti -1c
.RI "typedef std::vector< LayerData > \fBwpc::LayerDataVector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Default web browser start and image acquire methods\&. 


.PP
Definition in file \fBBasicLoader\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
