.TH "src/loader_traits.h" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/loader_traits.h \- 
.PP
Traits and defines for loader objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwpc::AppData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Traits and defines for loader objects\&. 


.PP
Definition in file \fBloader_traits\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
