.TH "src/pflow.h" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pflow.h \- 
.PP
Miscellaneous common defines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwpc::ProcessingFlow< L, C >\fP"
.br
.RI "\fIDescribes work flow process\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Miscellaneous common defines\&. 


.PP
Definition in file \fBpflow\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
