.TH "wpc::LayerData" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wpc::LayerData \- 
.PP
Layer descriptor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicLoader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "cv::Mat \fBimage\fP"
.br
.ti -1c
.RI "std::string \fBbrowser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Layer descriptor\&. 
.PP
Definition at line 64 of file BasicLoader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
