.TH "wpc::cmp_trait< BasicComparator >" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wpc::cmp_trait< BasicComparator > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double \fBresult_type\fP"
.br
.ti -1c
.RI "typedef 
.br
boost::signals2::signal< void(const 
.br
cv::Mat &, const cv::Mat &)> \fBcmp_call_sig\fP"
.br
.ti -1c
.RI "typedef std::vector< result_type > \fBdata_container_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>struct wpc::cmp_trait< BasicComparator >"

.PP
Definition at line 45 of file BasicComparator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
