.TH "wpc::AppData" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wpc::AppData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBwpc::BasicLoaderAppData\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 38 of file loader_traits\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
