.TH "wpc::cmp_trait< T >" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wpc::cmp_trait< T > \- 
.PP
Type trait for comparator types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comparator_traits\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct wpc::cmp_trait< T >"
Type trait for comparator types\&. 
.PP
Definition at line 39 of file comparator_traits\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
