.TH "wpc::BasicLoader" 3 "Wed Aug 6 2014" "Version 1.0.0" "WebPage Comparator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wpc::BasicLoader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const \fBAppData\fP &)"
.br
.ti -1c
.RI "void \fBsetComparatorObject\fP (const \fBcmp_trait\fP< \fBBasicComparator\fP >::cmp_call_sig::slot_type &st)"
.br
.RI "\fISets the comparison object used for comparing selected parts of web page\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file BasicLoader\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void wpc::BasicLoader::setComparatorObject (const \fBcmp_trait\fP< \fBBasicComparator\fP >::cmp_call_sig::slot_type &st)\fC [inline]\fP"

.PP
Sets the comparison object used for comparing selected parts of web page\&. \fBParameters:\fP
.RS 4
\fIst\fP - comparison object 
.RE
.PP

.PP
Definition at line 107 of file BasicLoader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebPage Comparator from the source code\&.
